### PR TITLE
fix setting phone without updating flag

### PR DESCRIPTION
**Pull request by fvolchyok**
fixes https://github.com/chronotruck/CTKFlagPhoneNumber/issues/4

### CODE REVIEW

**Comment by grifas** [comment]
I tried your code and that doesn't change anything.

If you want to change programmatically the flag and the phone number, put this lines in your code:
`
phoneNumberTextField.setFlag(with: "BY")
phoneNumberTextField.set(phoneNumber: "291234567")
`

**Comment by fvolchyok** [comment]
I'm afraid you didn't understand me correctly - the bug is when you set phone without knowing exactly what country it belongs (of course, you can _always_ use libPhoneNumber directly and check what country you should set, but it seems like bad practice), and it's country differs from the previous one the flag doesn't changes automatically. Event though I see correct phone for Belarus, for example, I still see American flag. You, on the other hand propose to always check for country and thus force users to do triple work: check for country, set correct flag, and only then set phone itself.
If it makes any sense - the phone I was setting was not in format 291234567, I set exactly "+375291234567". I was setting it already with code. Maybe it is the source of our misunderstanding.

**Comment by grifas** [comment]
Yes I spoke too fast ^^'
Ok, I understood now. It seems to be ok.

**Comment by maffpool** [comment]
Thanks @fvolchyok for your issue and your PR, much appreciated :)

**Pull request merged**
